version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: total_pos
      PGDATA: /var/lib/postgresql/data/pgdata
